# rustfmt doc - https://rust-lang.github.io/rustfmt/

comment_width = 10000
edition = "2021"
enum_discrim_align_threshold = 30
format_strings = true
max_width = 120
reorder_imports = true
tab_spaces = 2
wrap_comments = true
